{
    var data = {
        "light gold": ["2 light lime", "1 faded green", "3 clear olive", "2 dim bronze"],
        "muted beige": ["3 clear lime", "5 dark salmon", "1 pale olive"],
        "vibrant violet": ["3 dark tomato", "3 muted indigo", "3 plaid turquoise", "3 light silver"],
        "dull purple": ["2 wavy turquoise"],
        "posh purple": ["4 bright lavender", "2 wavy chartreuse", "3 vibrant aqua"],
        "striped gold": ["4 light magenta"],
        "dark lime": ["3 plaid brown"],
        "shiny salmon": ["5 light olive"],
        "dull gold": ["2 dim plum"],
        "dim olive": ["3 faded cyan"],
        "faded white": ["2 clear brown", "1 mirrored green", "3 plaid bronze"],
        "dull salmon": ["1 plaid gray", "4 vibrant aqua", "5 mirrored cyan"],
        "striped orange": ["4 vibrant maroon", "2 dark orange"],
        "dotted silver": ["2 posh red", "1 muted yellow", "5 light aqua", "3 pale red"],
        "light orange": ["1 striped coral", "3 dim lime", "4 muted yellow"],
        "wavy lime": ["5 light silver", "1 bright coral", "5 drab silver", "1 dark plum"],
        "bright tan": ["3 clear magenta", "2 muted white", "2 drab beige", "5 plaid green"],
        "dim violet": ["1 striped fuchsia", "2 mirrored green", "1 bright teal"],
        "mirrored gold": ["1 pale aqua"],
        "bright plum": ["1 faded fuchsia"],
        "muted aqua": ["2 muted red"],
        "plaid bronze": ["2 dim lime", "2 wavy coral", "1 vibrant lime", "1 dotted beige"],
        "dim chartreuse": ["5 mirrored lime", "2 dotted tomato", "1 plaid turquoise"],
        "muted lavender": ["4 faded salmon", "3 bright white", "3 posh fuchsia", "1 dotted green"],
        "mirrored yellow": ["1 wavy purple", "5 shiny teal", "5 shiny cyan", "1 shiny crimson"],
        "striped magenta": ["4 dim white", "2 pale white"],
        "dull crimson": ["3 muted black", "4 dull lavender"],
        "mirrored beige": ["2 posh indigo", "3 shiny gray"],
        "bright blue": ["5 mirrored fuchsia"],
        "plaid beige": ["3 mirrored cyan", "1 vibrant tan", "5 muted purple", "1 wavy red"],
        "dotted indigo": ["5 pale fuchsia", "5 posh tomato"],
        "muted coral": ["4 dim crimson", "3 dark brown", "2 drab fuchsia"],
        "drab tomato": ["1 muted tan", "2 dark salmon", "4 faded red", "5 shiny olive"],
        "dark tomato": ["5 mirrored salmon"],
        "bright yellow": ["4 light teal", "1 posh white", "2 shiny blue"],
        "dotted salmon": ["3 drab olive"],
        "vibrant olive": ["2 posh teal", "1 clear aqua"],
        "dotted gold": ["4 striped violet"],
        "light tan": ["2 plaid fuchsia", "1 faded turquoise", "2 muted tomato"],
        "drab orange": ["3 wavy violet", "1 dark fuchsia", "2 mirrored green"],
        "dull coral": ["1 dark crimson"],
        "light purple": ["4 dark gold", "3 plaid purple", "4 clear chartreuse"],
        "wavy yellow": ["3 striped silver", "2 dull chartreuse"],
        "dull tan": ["1 dim gold"],
        "vibrant plum": ["4 dotted turquoise", "1 faded gray"],
        "wavy tan": ["4 shiny plum", "5 faded white", "1 plaid plum"],
        "dim indigo": ["2 clear blue"],
        "muted teal": ["4 mirrored fuchsia", "5 faded black"],
        "dark maroon": ["5 mirrored gold", "5 bright red", "1 faded gray"],
        "mirrored aqua": ["4 faded turquoise", "1 mirrored tan"],
        "muted violet": ["4 mirrored lavender", "3 faded salmon"],
        "wavy orange": ["3 drab crimson", "5 posh indigo", "2 faded cyan", "5 light blue"],
        "mirrored blue": ["1 dark teal", "4 pale orange"],
        "muted silver": ["2 dim orange", "1 posh plum", "2 wavy fuchsia"],
        "plaid magenta": ["3 faded blue", "5 vibrant lime", "2 faded beige"],
        "dark lavender": ["3 clear olive"],
        "posh salmon": ["4 dark orange"],
        "dim silver": ["3 plaid blue", "1 posh brown", "1 striped white"],
        "posh chartreuse": ["3 drab plum", "3 mirrored brown"],
        "shiny cyan": ["4 faded plum", "5 wavy yellow", "2 drab maroon"],
        "drab bronze": ["2 shiny turquoise", "4 faded white", "4 drab white"],
        "dotted cyan": ["1 posh brown", "2 dark orange", "4 plaid bronze"],
        "shiny beige": ["5 dotted cyan", "2 pale indigo"],
        "drab violet": ["4 posh chartreuse", "1 drab fuchsia"],
        "muted tomato": ["2 posh aqua"],
        "drab plum": ["5 drab gold", "4 dark fuchsia", "5 pale gold", "3 dim olive"],
        "dim brown": ["1 drab indigo", "2 pale gold", "5 posh fuchsia"],
        "plaid cyan": ["1 light orange", "2 bright violet"],
        "striped silver": ["2 shiny silver"],
        "plaid tomato": ["3 drab cyan", "4 clear chartreuse", "3 dim coral", "4 shiny gray"],
        "posh tomato": ["1 plaid bronze", "1 dim lime"],
        "vibrant orange": ["5 bright aqua", "2 drab coral", "4 dull aqua", "3 vibrant lavender"],
        "drab brown": ["1 bright orange", "3 drab salmon"],
        "plaid crimson": ["3 dull red", "3 posh maroon", "2 dull beige"],
        "clear aqua": ["5 muted cyan", "1 dotted teal"],
        "pale magenta": ["2 light brown"],
        "mirrored chartreuse": ["3 striped gold", "3 light silver", "3 dim red", "3 dim chartreuse"],
        "mirrored plum": ["2 striped tomato", "1 posh aqua", "1 muted teal", "2 faded indigo"],
        "posh teal": ["5 clear indigo", "5 plaid purple", "4 pale white", "3 drab gray"],
        "wavy aqua": ["4 drab beige", "5 plaid black"],
        "drab coral": ["3 striped tomato", "1 dotted cyan"],
        "shiny chartreuse": ["2 mirrored cyan"],
        "striped gray": ["5 striped tomato"],
        "shiny orange": ["4 muted purple", "4 dim silver", "5 shiny gold", "3 pale orange"],
        "dark teal": ["no other"],
        "dark magenta": ["4 pale gray", "1 dim purple", "4 drab coral"],
        "vibrant fuchsia": ["4 dull olive"],
        "light bronze": ["2 plaid gold", "2 dark white"],
        "dotted yellow": ["5 bright indigo", "2 light silver", "3 wavy red"],
        "muted purple": ["1 shiny blue", "5 faded red", "1 dim olive"],
        "faded cyan": ["1 dark teal"],
        "dull brown": ["5 vibrant aqua"],
        "shiny white": ["2 dull red", "1 plaid orange", "5 muted turquoise"],
        "light brown": ["4 dim coral", "3 faded red"],
        "bright orange": ["5 dull olive"],
        "light lime": ["4 light magenta", "5 muted violet"],
        "shiny indigo": ["2 bright blue", "1 dotted turquoise", "2 clear bronze"],
        "faded teal": ["4 bright brown", "1 light silver"],
        "posh bronze": ["3 dark salmon", "2 plaid fuchsia", "1 dim white", "5 faded maroon"],
        "shiny yellow": ["1 posh lime"],
        "dotted beige": ["no other"],
        "vibrant blue": ["2 posh green", "1 faded white", "2 plaid red", "4 posh violet"],
        "posh lime": ["4 bright aqua"],
        "posh coral": ["5 plaid white", "3 faded coral"],
        "dark yellow": ["3 wavy violet", "5 clear chartreuse", "5 light turquoise"],
        "wavy bronze": ["2 clear brown", "2 muted cyan"],
        "faded brown": ["5 dim lime", "4 dotted beige", "3 wavy coral", "1 faded gray"],
        "vibrant gold": ["2 dotted maroon"],
        "vibrant red": ["4 dull black"],
        "clear beige": ["4 dim olive", "3 plaid bronze", "3 clear brown", "5 vibrant lime"],
        "dim teal": ["4 plaid bronze", "5 striped tan", "1 muted olive"],
        "dim aqua": ["1 faded lime", "4 faded gray", "1 posh coral"],
        "faded tan": ["5 clear lime", "4 shiny violet", "2 dull aqua"],
        "mirrored green": ["no other"],
        "light magenta": ["5 plaid gold"],
        "striped white": ["1 wavy coral", "1 faded gray", "3 vibrant lime", "2 mirrored fuchsia"],
        "plaid violet": ["3 faded indigo", "1 striped fuchsia", "5 drab salmon", "4 mirrored cyan"],
        "dull cyan": ["4 dark chartreuse", "3 light gray"],
        "light salmon": ["2 dark teal"],
        "drab crimson": ["3 vibrant tan"],
        "striped yellow": ["5 faded brown", "4 posh olive"],
        "pale orange": ["no other"],
        "faded gold": ["5 light magenta"],
        "faded beige": ["1 faded indigo", "5 wavy green", "5 faded crimson"],
        "striped crimson": ["2 posh brown"],
        "dark black": ["4 plaid lavender", "5 mirrored salmon"],
        "bright beige": ["1 bright brown", "5 posh aqua"],
        "bright gold": ["3 light lime", "2 shiny white"],
        "bright tomato": ["4 dull orange", "4 dull blue"],
        "light olive": ["4 dull blue", "4 plaid gray", "4 faded gray"],
        "vibrant lavender": ["1 clear salmon", "2 bright lavender"],
        "drab yellow": ["1 plaid black"],
        "faded green": ["1 clear brown", "4 mirrored orange", "1 striped tan"],
        "vibrant black": ["4 mirrored fuchsia"],
        "bright indigo": ["5 plaid red", "1 striped chartreuse", "3 vibrant plum", "5 dark lavender"],
        "dull plum": ["2 mirrored plum", "2 light silver", "1 pale indigo"],
        "striped bronze": ["2 dotted blue"],
        "muted magenta": ["2 dim silver", "5 clear purple"],
        "striped teal": ["5 vibrant white"],
        "dim bronze": ["2 dim crimson", "4 vibrant beige", "2 wavy turquoise"],
        "shiny lavender": ["4 dim purple"],
        "vibrant silver": ["1 dotted crimson", "2 dotted maroon"],
        "posh yellow": ["4 bright salmon", "4 shiny lavender", "5 mirrored aqua"],
        "faded bronze": ["2 posh brown", "3 clear lime", "4 dotted red", "2 striped white"],
        "posh maroon": ["5 striped salmon", "1 light black"],
        "pale aqua": ["2 shiny orange", "1 shiny silver", "2 dim violet"],
        "plaid chartreuse": ["2 muted black", "4 muted magenta", "1 mirrored bronze", "1 posh beige"],
        "dotted orange": ["2 drab indigo"],
        "plaid gold": ["3 drab beige"],
        "shiny silver": ["2 dull teal", "5 drab gray", "4 bright blue", "2 dotted cyan"],
        "mirrored crimson": ["2 shiny gold", "5 plaid black", "3 drab beige", "1 pale beige"],
        "pale gold": ["1 striped tomato", "5 striped white", "2 mirrored bronze", "5 dim orange"],
        "vibrant crimson": ["5 faded white", "2 wavy coral"],
        "dim yellow": ["1 vibrant coral", "5 faded red", "4 mirrored magenta", "4 posh indigo"],
        "dull teal": ["1 plaid fuchsia", "3 striped blue"],
        "striped red": ["4 dull lime"],
        "muted chartreuse": ["5 bright crimson"],
        "dim lavender": ["2 posh maroon"],
        "wavy crimson": ["1 dim magenta", "4 dim crimson", "1 dull lavender", "3 muted fuchsia"],
        "dull green": ["5 dull olive", "1 clear blue", "5 shiny salmon"],
        "wavy red": ["1 dull chartreuse", "3 dim black"],
        "pale blue": ["4 light olive", "3 vibrant chartreuse"],
        "dull fuchsia": ["2 posh chartreuse"],
        "dotted violet": ["1 shiny olive", "3 bright blue", "5 posh beige", "4 vibrant black"],
        "drab white": ["1 plaid gold", "5 clear olive"],
        "drab blue": ["3 muted bronze", "5 shiny gold", "4 dim olive"],
        "plaid salmon": ["5 pale gold"],
        "pale coral": ["3 plaid orange", "3 plaid fuchsia", "5 drab teal"],
        "vibrant maroon": ["3 dim lime", "2 pale beige", "5 mirrored green"],
        "mirrored magenta": ["2 striped blue"],
        "faded blue": ["3 vibrant bronze", "2 clear maroon", "1 faded white", "3 dark cyan"],
        "drab olive": ["5 wavy teal", "3 mirrored black", "5 dark gray", "5 dull lime"],
        "posh white": ["1 plaid purple", "4 dark turquoise", "3 clear salmon", "1 dim orange"],
        "dull red": ["4 vibrant plum", "3 plaid black", "4 dull orange"],
        "striped tan": ["no other"],
        "posh blue": ["3 mirrored magenta", "1 dark plum", "4 wavy turquoise", "1 shiny coral"],
        "drab salmon": ["2 bright aqua", "4 posh gold", "5 plaid blue"],
        "striped green": ["5 dim black"],
        "wavy salmon": ["5 pale purple"],
        "vibrant cyan": ["1 dark gray", "1 vibrant beige", "5 drab violet", "5 dull coral"],
        "wavy lavender": ["1 light magenta", "2 striped cyan"],
        "faded maroon": ["5 light gray"],
        "vibrant yellow": ["2 bright beige", "5 dim brown", "2 posh silver", "2 pale cyan"],
        "dotted tomato": ["3 mirrored magenta", "3 wavy chartreuse", "2 wavy maroon"],
        "striped lavender": ["4 shiny coral", "2 dim white", "3 faded red"],
        "faded red": ["2 mirrored fuchsia", "1 light cyan", "2 vibrant lime", "1 mirrored green"],
        "clear black": ["3 drab purple", "2 bright yellow", "2 wavy brown"],
        "faded indigo": ["1 dim lime", "1 clear brown"],
        "shiny tan": ["1 dull brown", "2 striped tomato"],
        "drab teal": ["1 dotted turquoise", "4 posh fuchsia"],
        "wavy magenta": ["1 dim yellow", "3 drab indigo"],
        "mirrored turquoise": ["no other"],
        "faded lime": ["4 drab cyan", "1 clear orange", "5 vibrant salmon", "5 faded crimson"],
        "vibrant coral": ["5 pale gray", "2 clear salmon"],
        "muted turquoise": ["1 clear brown"],
        "plaid aqua": ["3 dull coral"],
        "pale indigo": ["1 striped brown", "2 bright cyan", "5 plaid silver"],
        "faded tomato": ["1 pale red", "2 dotted tan"],
        "mirrored white": ["4 drab fuchsia", "3 plaid orange", "4 dotted lavender"],
        "shiny aqua": ["1 wavy silver", "4 drab green", "1 bright tomato"],
        "pale cyan": ["1 pale gold", "5 dark turquoise"],
        "mirrored salmon": ["5 light crimson", "5 muted bronze", "2 vibrant beige", "1 striped lavender"],
        "dark gold": ["1 shiny olive"],
        "muted blue": ["2 vibrant maroon", "5 wavy chartreuse"],
        "bright fuchsia": ["1 posh white"],
        "light blue": ["5 muted beige", "1 dark crimson", "5 mirrored brown", "1 posh orange"],
        "clear salmon": ["1 faded brown", "5 dotted beige", "4 faded gray", "4 dark orange"],
        "plaid red": ["3 drab silver", "2 dim green"],
        "faded plum": ["2 posh orange", "5 dotted lime"],
        "bright coral": ["3 plaid plum", "1 dark green", "2 striped crimson", "5 vibrant coral"],
        "shiny crimson": ["5 bright teal", "4 muted magenta", "4 vibrant maroon", "3 faded cyan"],
        "dim magenta": ["1 muted olive", "1 bright blue", "4 muted white", "5 posh gray"],
        "pale brown": ["4 dotted cyan", "5 bright coral"],
        "striped olive": ["2 bright brown", "4 pale gray", "5 dotted teal", "3 pale white"],
        "posh gray": ["1 dark chartreuse"],
        "dotted brown": ["3 plaid gold", "5 dim bronze"],
        "dim lime": ["no other"],
        "clear crimson": ["2 posh orange", "2 plaid plum", "1 dark orange"],
        "shiny turquoise": ["1 faded indigo", "3 light red"],
        "striped plum": ["1 muted white"],
        "muted crimson": ["1 bright teal"],
        "plaid blue": ["3 dotted beige", "5 vibrant lime", "1 vibrant tan", "2 striped blue"],
        "light teal": ["2 dotted cyan"],
        "faded salmon": ["5 mirrored crimson"],
        "shiny blue": ["4 posh gold", "3 light cyan", "1 clear teal"],
        "plaid brown": ["2 dull lavender"],
        "muted bronze": ["3 faded purple"],
        "posh fuchsia": ["5 striped coral"],
        "clear orange": ["1 bright blue", "5 posh gold", "5 striped crimson", "1 dark teal"],
        "plaid plum": ["5 faded brown"],
        "clear gray": ["4 mirrored fuchsia", "2 dim cyan", "3 pale gold", "1 dim violet"],
        "bright lavender": ["1 mirrored purple", "4 wavy magenta", "2 dull black", "3 light silver"],
        "pale purple": ["3 striped tan", "1 dull olive"],
        "pale bronze": ["2 plaid aqua", "2 pale fuchsia", "4 bright lime"],
        "clear blue": ["3 plaid beige"],
        "drab silver": ["3 dim violet", "1 muted yellow", "1 pale beige"],
        "dark silver": ["4 dark fuchsia", "4 bright green", "5 dim beige", "1 light tomato"],
        "mirrored gray": ["2 striped black"],
        "posh black": ["3 dull indigo", "3 striped beige", "3 dim blue", "2 wavy lime"],
        "clear teal": ["2 dark orange", "4 pale beige", "5 clear beige", "4 dark teal"],
        "pale white": ["2 drab gray", "1 muted olive"],
        "muted fuchsia": ["2 clear brown", "4 mirrored green", "2 striped tan"],
        "bright cyan": ["1 dotted plum"],
        "light tomato": ["2 dim violet", "1 pale green", "4 dim orange", "1 dotted tomato"],
        "pale turquoise": ["2 plaid black", "2 clear brown"],
        "dim orange": ["1 plaid plum", "2 clear indigo", "1 dotted blue", "1 drab beige"],
        "posh red": ["5 faded brown", "4 clear gray", "5 bright teal"],
        "bright teal": ["4 clear beige"],
        "posh lavender": ["1 drab beige", "5 dim salmon", "3 light crimson"],
        "drab green": ["1 striped brown", "1 dull blue", "1 plaid coral"],
        "clear coral": ["1 faded crimson", "4 light silver", "1 posh violet"],
        "dark tan": ["5 faded brown"],
        "vibrant aqua": ["1 light cyan", "5 bright brown"],
        "dark blue": ["1 dark silver"],
        "drab lime": ["3 faded white", "5 clear tomato", "1 dark turquoise"],
        "faded lavender": ["1 bright violet", "4 posh gold"],
        "dark orange": ["2 striped tan"],
        "plaid orange": ["4 dark beige", "5 dull lavender", "4 striped white"],
        "vibrant chartreuse": ["1 faded indigo", "4 clear magenta", "2 shiny blue", "2 dull teal"],
        "dim white": ["3 faded white", "2 clear teal"],
        "dim cyan": ["4 clear olive", "4 pale gray", "5 plaid bronze"],
        "dotted chartreuse": ["1 bright magenta", "5 shiny maroon"],
        "dull aqua": ["2 drab beige"],
        "clear violet": ["3 pale teal", "3 posh tomato", "1 light silver", "2 faded coral"],
        "pale lavender": ["1 drab beige", "2 dark teal"],
        "clear tomato": ["5 muted beige", "1 plaid gold", "3 vibrant coral", "3 shiny silver"],
        "clear cyan": ["4 faded lime", "2 drab tomato"],
        "striped salmon": ["3 dim silver"],
        "wavy silver": ["2 drab blue", "4 shiny green", "3 muted yellow"],
        "dull indigo": ["5 mirrored plum"],
        "faded coral": ["2 muted olive", "4 dark salmon"],
        "muted olive": ["5 faded red", "1 dim lime", "1 striped white", "4 dark teal"],
        "dotted plum": ["5 plaid blue"],
        "striped cyan": ["4 mirrored plum", "2 wavy beige"],
        "dotted olive": ["3 mirrored gold", "4 bright lavender", "2 dim turquoise"],
        "plaid green": ["5 dark chartreuse", "5 mirrored bronze", "5 dark beige"],
        "clear chartreuse": ["5 posh olive", "3 plaid violet", "3 mirrored fuchsia", "2 light orange"],
        "wavy indigo": ["2 shiny teal", "3 clear olive"],
        "shiny fuchsia": ["5 striped chartreuse", "1 light chartreuse"],
        "shiny coral": ["4 dotted plum", "4 dull orange", "3 posh olive", "2 dark salmon"],
        "bright black": ["5 drab gray", "1 vibrant black", "3 vibrant salmon", "3 dim silver"],
        "bright salmon": ["1 shiny plum", "4 bright brown", "5 pale gray", "3 mirrored maroon"],
        "faded yellow": ["1 light blue", "2 striped white", "3 dim lime", "4 wavy cyan"],
        "plaid fuchsia": ["1 striped blue"],
        "plaid lime": ["3 clear bronze", "4 dull orange", "1 pale aqua"],
        "clear turquoise": ["1 posh aqua", "5 plaid black", "4 vibrant brown"],
        "dull lime": ["3 mirrored crimson", "1 dotted crimson", "2 light lime", "2 light gray"],
        "dull gray": ["5 bright lavender", "3 muted olive"],
        "dotted turquoise": ["2 dim olive", "1 striped blue", "4 clear indigo"],
        "vibrant purple": ["4 light olive", "4 mirrored salmon", "4 muted red"],
        "dark cyan": ["2 dim lime", "5 light olive", "4 muted red", "3 drab indigo"],
        "vibrant turquoise": ["4 light indigo"],
        "bright bronze": ["2 pale green", "5 faded gray"],
        "clear maroon": ["3 faded coral"],
        "faded purple": ["5 plaid plum", "3 striped blue", "2 vibrant tan", "3 dark orange"],
        "light indigo": ["2 wavy bronze", "5 bright lime", "4 drab lime", "2 dotted chartreuse"],
        "dotted bronze": ["5 faded brown", "4 drab silver", "3 drab chartreuse"],
        "mirrored lavender": ["3 dim salmon"],
        "clear gold": ["1 dull plum"],
        "vibrant beige": ["5 drab crimson"],
        "dull yellow": ["5 mirrored green", "4 plaid bronze", "5 plaid blue", "4 dull orange"],
        "dotted black": ["2 dull fuchsia", "2 light fuchsia", "3 mirrored lavender", "1 muted coral"],
        "dotted maroon": ["3 plaid coral", "5 dotted cyan"],
        "dim tomato": ["4 pale tomato", "3 striped beige"],
        "wavy violet": ["4 mirrored crimson", "4 plaid bronze", "4 faded turquoise", "4 drab chartreuse"],
        "shiny bronze": ["3 muted chartreuse", "3 drab gold"],
        "faded fuchsia": ["1 bright blue", "1 dim purple", "1 dim magenta"],
        "plaid turquoise": ["2 shiny olive", "5 dull orange", "2 dark fuchsia", "3 clear purple"],
        "mirrored teal": ["4 drab cyan", "2 striped green"],
        "clear purple": ["3 dull teal", "2 vibrant tan", "5 vibrant maroon"],
        "dotted blue": ["2 muted white", "2 dark green", "2 faded purple", "2 plaid blue"],
        "light violet": ["5 dark salmon", "5 striped orange"],
        "light beige": ["2 muted chartreuse", "4 striped brown", "3 wavy maroon"],
        "wavy purple": ["4 dark violet", "3 drab fuchsia", "4 dull lavender", "3 drab lime"],
        "light silver": ["4 posh brown", "3 vibrant crimson"],
        "wavy white": ["5 mirrored fuchsia", "2 dotted turquoise", "5 striped tomato"],
        "striped purple": ["4 dull chartreuse"],
        "wavy teal": ["1 light chartreuse", "3 dark green"],
        "vibrant indigo": ["2 dim coral"],
        "pale red": ["3 drab cyan", "1 muted tan"],
        "dark aqua": ["2 faded brown", "1 shiny gold", "3 light cyan", "2 light green"],
        "dotted tan": ["2 drab beige", "2 faded gray"],
        "faded aqua": ["5 faded brown"],
        "drab turquoise": ["5 drab teal"],
        "dark turquoise": ["2 dim teal", "1 dim coral", "1 clear beige"],
        "wavy maroon": ["1 dim violet", "4 clear bronze"],
        "dark gray": ["2 bright blue"],
        "mirrored coral": ["1 clear lime", "1 posh gray"],
        "dim red": ["3 plaid aqua", "4 plaid salmon", "3 pale gray", "4 wavy indigo"],
        "dull maroon": ["3 light silver", "1 dim lime", "2 striped silver"],
        "vibrant salmon": ["1 dark gray", "2 dotted cyan", "2 drab gray", "3 muted tan"],
        "vibrant lime": ["no other"],
        "wavy blue": ["5 bright maroon", "2 dull plum", "4 pale magenta"],
        "dim purple": ["3 dull indigo"],
        "muted indigo": ["5 posh orange", "4 dim yellow"],
        "posh gold": ["2 clear beige", "3 vibrant lime"],
        "plaid purple": ["4 faded brown", "3 shiny blue", "1 faded white"],
        "clear lime": ["5 posh aqua", "2 posh fuchsia", "1 clear teal", "4 faded cyan"],
        "bright brown": ["5 plaid bronze", "4 faded indigo"],
        "striped maroon": ["1 faded turquoise", "3 drab cyan", "5 dark gray", "2 pale black"],
        "faded violet": ["4 drab crimson"],
        "muted brown": ["2 bright tomato", "3 dim gold", "5 dull blue"],
        "posh magenta": ["2 dark fuchsia"],
        "vibrant green": ["3 dark fuchsia"],
        "shiny tomato": ["2 light turquoise", "5 drab green", "1 posh gold"],
        "faded olive": ["1 shiny purple", "4 wavy tan", "4 wavy violet", "1 muted fuchsia"],
        "mirrored fuchsia": ["1 clear brown"],
        "faded magenta": ["3 striped white", "3 posh tomato", "3 striped lime"],
        "dim crimson": ["5 mirrored brown", "1 faded black", "1 dark orange"],
        "dark green": ["2 dotted beige", "5 plaid blue"],
        "dotted purple": ["4 shiny black", "1 muted violet", "1 drab green", "3 faded yellow"],
        "posh turquoise": ["3 shiny plum"],
        "muted gray": ["4 dull gray", "4 posh teal", "5 plaid gray"],
        "shiny teal": ["2 pale beige"],
        "shiny olive": ["1 striped tan", "3 mirrored turquoise"],
        "dull white": ["2 pale orange", "1 dim magenta", "4 drab maroon"],
        "drab aqua": ["1 wavy red"],
        "dotted teal": ["3 shiny green", "3 drab beige", "1 drab crimson"],
        "light cyan": ["2 mirrored green", "5 dotted beige", "5 faded white", "3 mirrored fuchsia"],
        "dim maroon": ["1 drab fuchsia", "1 mirrored salmon"],
        "mirrored maroon": ["4 muted white", "2 striped tan", "2 dark teal"],
        "dark brown": ["1 striped bronze", "5 striped plum", "3 muted bronze", "2 striped lime"],
        "plaid gray": ["1 clear brown", "5 shiny orange", "4 posh bronze", "5 light cyan"],
        "dim gold": ["4 striped tomato", "5 striped fuchsia", "4 striped white", "1 clear brown"],
        "drab tan": ["5 plaid fuchsia", "1 dim teal", "4 plaid gold"],
        "bright aqua": ["4 faded indigo", "3 shiny blue", "4 posh aqua", "5 wavy tan"],
        "pale lime": ["4 muted blue", "5 wavy purple"],
        "plaid maroon": ["2 dim black", "1 drab indigo"],
        "wavy gray": ["4 drab orange"],
        "drab gold": ["1 dark gray", "4 pale gold"],
        "plaid teal": ["2 dim teal", "1 vibrant lavender"],
        "dark salmon": ["4 plaid black", "2 dim lime", "4 pale orange", "3 pale beige"],
        "plaid lavender": ["3 faded red", "2 plaid aqua"],
        "light fuchsia": ["3 dim violet"],
        "faded chartreuse": ["2 mirrored gold", "5 drab gold", "3 mirrored salmon"],
        "wavy beige": ["2 dotted salmon", "4 muted white"],
        "striped tomato": ["4 drab cyan"],
        "dotted white": ["4 bright green", "1 light brown"],
        "muted yellow": ["3 dim violet", "1 posh aqua", "2 muted teal"],
        "light chartreuse": ["4 posh aqua", "2 dim coral"],
        "muted maroon": ["1 mirrored cyan", "4 dim olive"],
        "pale yellow": ["3 bright olive"],
        "dull bronze": ["2 plaid maroon", "2 vibrant bronze"],
        "shiny gold": ["5 clear brown", "5 plaid fuchsia", "4 bright teal", "1 striped white"],
        "posh crimson": ["4 vibrant plum"],
        "clear silver": ["5 dim beige", "1 dark olive"],
        "striped violet": ["5 posh orange", "1 vibrant crimson"],
        "muted green": ["1 bright crimson"],
        "shiny gray": ["4 striped maroon", "5 muted plum", "2 light chartreuse"],
        "wavy turquoise": ["1 pale gold"],
        "clear olive": ["4 plaid fuchsia"],
        "drab indigo": ["1 clear purple", "4 light silver", "2 mirrored cyan", "2 clear lime"],
        "dim salmon": ["1 pale aqua", "5 posh fuchsia", "4 plaid coral", "1 pale orange"],
        "light black": ["3 muted chartreuse"],
        "plaid indigo": ["3 plaid fuchsia", "2 muted tomato", "3 muted bronze", "1 drab white"],
        "light crimson": ["2 striped chartreuse", "4 bright teal", "3 striped fuchsia"],
        "bright purple": ["2 shiny violet"],
        "dark bronze": ["3 striped violet", "4 clear beige"],
        "dark white": ["5 faded white", "5 striped fuchsia", "2 vibrant lime", "5 striped tan"],
        "mirrored orange": ["4 wavy aqua"],
        "mirrored cyan": ["5 bright bronze"],
        "dull blue": ["2 bright brown", "2 dim plum"],
        "posh indigo": ["1 posh lime"],
        "vibrant brown": ["1 bright indigo", "2 striped purple", "5 mirrored lime", "2 plaid plum"],
        "wavy coral": ["no other"],
        "posh cyan": ["1 plaid plum", "2 plaid gold", "3 shiny plum"],
        "vibrant tan": ["5 mirrored turquoise", "3 faded gray", "5 posh brown", "3 clear brown"],
        "mirrored black": ["5 striped fuchsia", "1 striped tan", "3 pale green"],
        "bright olive": ["1 bright orange", "4 drab gold", "3 dim cyan", "2 drab plum"],
        "striped blue": ["3 dark white", "1 clear beige", "3 dim olive"],
        "dim turquoise": ["4 muted turquoise", "1 dotted tomato", "4 muted brown"],
        "posh green": ["4 dim gray", "4 clear brown"],
        "dull magenta": ["3 bright plum"],
        "dark red": ["2 muted magenta", "2 dark beige", "2 shiny black"],
        "pale black": ["2 striped bronze"],
        "dotted red": ["2 striped blue", "3 dim violet", "3 faded maroon"],
        "dark chartreuse": ["5 striped orange", "5 dark white"],
        "clear lavender": ["2 faded crimson", "5 clear purple", "3 vibrant tan"],
        "vibrant white": ["1 drab crimson", "5 dim violet"],
        "drab lavender": ["3 clear yellow", "5 shiny tan"],
        "wavy cyan": ["5 shiny violet"],
        "faded black": ["2 posh aqua", "5 bright teal", "1 posh orange", "4 vibrant coral"],
        "mirrored tomato": ["3 muted cyan", "3 drab brown", "1 striped orange"],
        "faded orange": ["3 plaid fuchsia", "5 mirrored crimson", "2 pale aqua", "2 dull lavender"],
        "muted salmon": ["1 wavy tan", "2 muted chartreuse", "2 posh green", "5 shiny magenta"],
        "pale plum": ["4 dull teal", "1 striped violet", "2 wavy crimson", "2 posh violet"],
        "shiny magenta": ["3 muted yellow", "5 light beige", "1 dull white", "4 striped lavender"],
        "plaid black": ["4 mirrored green"],
        "clear plum": ["5 posh violet"],
        "bright silver": ["2 dull yellow", "3 striped red", "3 dotted olive", "5 bright salmon"],
        "muted gold": ["1 dull olive"],
        "vibrant tomato": ["4 shiny blue", "1 bright indigo"],
        "dim black": ["1 plaid gold", "2 muted white"],
        "plaid white": ["2 muted cyan", "1 mirrored magenta", "3 striped red", "2 striped violet"],
        "drab maroon": ["1 dotted cyan", "3 shiny orange"],
        "shiny purple": ["3 posh purple"],
        "shiny violet": ["3 dark teal", "3 shiny olive", "4 dull cyan", "1 dim plum"],
        "dull chartreuse": ["2 bright tan", "2 wavy fuchsia", "4 bright teal", "1 posh violet"],
        "striped fuchsia": ["5 dotted beige"],
        "muted lime": ["1 vibrant tan"],
        "dotted coral": ["5 mirrored magenta", "4 wavy blue"],
        "bright turquoise": ["5 pale indigo"],
        "bright maroon": ["4 plaid salmon", "3 wavy coral", "4 dull orange", "1 pale green"],
        "dim green": ["4 posh olive", "4 dim white", "3 clear orange"],
        "mirrored bronze": ["4 mirrored fuchsia"],
        "shiny maroon": ["1 wavy maroon", "1 drab gray", "1 posh white"],
        "wavy olive": ["1 muted purple", "1 shiny brown", "5 faded tomato"],
        "dotted crimson": ["2 shiny blue", "4 dotted blue", "5 vibrant crimson"],
        "mirrored olive": ["3 muted bronze", "1 drab tomato", "3 drab violet"],
        "light aqua": ["3 faded cyan", "4 shiny white"],
        "clear fuchsia": ["3 bright blue"],
        "light green": ["2 dim brown", "4 drab green"],
        "bright magenta": ["1 mirrored turquoise", "2 dark fuchsia", "5 shiny plum"],
        "pale fuchsia": ["4 wavy purple", "2 striped salmon", "4 pale black", "3 dotted teal"],
        "posh tan": ["3 plaid purple"],
        "dull tomato": ["2 clear salmon", "2 striped yellow", "5 pale indigo"],
        "bright white": ["1 drab white", "4 dim violet"],
        "bright gray": ["5 muted yellow", "5 vibrant crimson"],
        "dull silver": ["2 muted purple"],
        "dotted gray": ["2 mirrored magenta", "1 dark lavender", "1 clear blue", "4 faded magenta"],
        "wavy gold": ["3 mirrored green", "5 pale aqua"],
        "shiny plum": ["5 plaid blue", "2 muted white", "5 pale gray", "2 faded indigo"],
        "posh plum": ["4 wavy magenta", "3 mirrored plum"],
        "clear bronze": ["4 bright aqua", "4 dim white", "4 plaid blue", "5 plaid black"],
        "vibrant teal": ["2 light violet", "4 clear orange", "1 shiny plum", "1 light cyan"],
        "clear red": ["2 drab tan"],
        "striped coral": ["1 shiny olive", "1 dark teal", "3 dark white"],
        "striped aqua": ["4 wavy teal", "2 dull chartreuse", "3 mirrored cyan", "5 plaid gray"],
        "drab purple": ["1 faded fuchsia", "5 dull chartreuse", "1 light white", "5 posh gold"],
        "mirrored brown": ["5 bright aqua", "5 shiny blue", "5 dotted blue", "1 posh fuchsia"],
        "dim gray": ["4 vibrant chartreuse", "5 clear beige", "1 shiny orange", "5 light chartreuse"],
        "mirrored purple": ["3 shiny gold", "4 plaid aqua", "4 wavy gold"],
        "drab black": ["4 faded aqua"],
        "pale tomato": ["3 vibrant gold", "2 dotted cyan", "3 wavy brown", "5 bright violet"],
        "muted plum": ["5 dull white", "5 drab chartreuse", "4 clear gray"],
        "bright lime": ["1 light chartreuse"],
        "light yellow": ["1 vibrant teal", "1 dull teal"],
        "dark fuchsia": ["3 dim plum", "5 faded purple"],
        "dim blue": ["5 striped coral", "3 drab fuchsia", "5 drab salmon"],
        "posh orange": ["2 pale gray", "4 plaid bronze", "5 vibrant tan"],
        "striped beige": ["3 mirrored crimson", "3 muted fuchsia"],
        "dim fuchsia": ["5 clear white"],
        "dull orange": ["2 striped crimson", "2 dark white", "1 dark turquoise", "3 shiny olive"],
        "drab fuchsia": ["3 dark crimson", "5 clear magenta", "5 faded brown"],
        "dim tan": ["3 dull indigo", "3 clear magenta"],
        "clear green": ["3 bright blue", "4 clear teal", "2 pale indigo"],
        "shiny black": ["1 mirrored brown"],
        "pale maroon": ["2 faded lime", "2 wavy red", "1 dark orange"],
        "faded crimson": ["1 posh aqua", "5 bright brown", "4 dull teal", "4 striped orange"],
        "muted tan": ["2 pale gold", "3 striped magenta", "5 plaid gold", "5 striped fuchsia"],
        "light turquoise": ["2 dull plum"],
        "dull lavender": ["3 dark green", "3 light brown", "2 posh fuchsia", "5 posh bronze"],
        "pale olive": ["5 striped blue", "1 striped coral", "2 muted white"],
        "dark crimson": ["1 bright red"],
        "vibrant gray": ["1 clear coral", "4 posh aqua", "5 clear brown", "5 dull chartreuse"],
        "plaid tan": ["2 bright coral", "3 wavy salmon"],
        "bright crimson": ["4 clear indigo", "3 dim plum", "4 posh brown"],
        "dotted magenta": ["5 bright lime", "2 dotted coral"],
        "posh aqua": ["5 vibrant lime", "5 plaid fuchsia"],
        "striped turquoise": ["5 pale lavender"],
        "pale chartreuse": ["4 mirrored tan", "5 mirrored black"],
        "pale tan": ["4 plaid beige", "3 light tomato", "1 dark tan", "4 faded lime"],
        "wavy plum": ["5 dark crimson", "4 dim black"],
        "posh brown": ["3 dark teal", "5 striped white"],
        "mirrored tan": ["3 clear maroon", "4 mirrored green", "1 dotted red", "1 wavy aqua"],
        "dotted fuchsia": ["3 clear lime", "2 dim plum", "2 bright salmon", "5 faded violet"],
        "drab cyan": ["4 striped coral", "5 faded gray", "2 posh orange"],
        "light red": ["5 faded black"],
        "plaid yellow": ["3 striped green", "4 striped olive", "1 mirrored lavender"],
        "muted black": ["2 muted turquoise", "3 wavy bronze", "5 wavy teal"],
        "plaid silver": ["2 drab maroon", "2 wavy maroon", "5 dark tan"],
        "dark coral": ["1 posh bronze", "5 bright coral"],
        "bright violet": ["3 posh brown", "4 pale orange", "2 muted olive", "2 posh orange"],
        "pale silver": ["3 pale fuchsia", "4 bright cyan"],
        "dim plum": ["1 faded brown"],
        "mirrored red": ["3 dull magenta", "2 light gold"],
        "posh beige": ["5 plaid turquoise", "3 clear bronze", "5 plaid silver"],
        "faded silver": ["4 muted violet", "3 muted tomato", "1 bright yellow"],
        "dim coral": ["1 faded brown", "4 drab cyan", "1 shiny olive"],
        "drab beige": ["5 mirrored fuchsia", "1 faded brown"],
        "dark purple": ["1 striped tan", "2 light maroon"],
        "drab magenta": ["4 dim silver", "4 mirrored silver", "5 muted tomato"],
        "muted orange": ["5 dim olive", "5 pale brown", "2 mirrored black", "3 posh green"],
        "dotted aqua": ["2 faded turquoise", "4 light yellow", "4 dotted lavender"],
        "pale salmon": ["4 light cyan", "4 bright plum"],
        "bright red": ["3 bright coral", "4 clear brown", "1 bright teal"],
        "striped lime": ["5 bright yellow", "1 drab maroon", "5 muted silver"],
        "clear magenta": ["5 light teal", "5 dotted cyan", "1 pale orange"],
        "dull beige": ["1 posh cyan", "5 dark orange", "3 pale cyan", "5 drab salmon"],
        "striped chartreuse": ["4 wavy maroon"],
        "pale gray": ["1 plaid black"],
        "dull black": ["3 dull brown"],
        "dotted green": ["3 shiny maroon"],
        "faded turquoise": ["2 dark violet"],
        "wavy green": ["5 light gray", "5 vibrant lime"],
        "light maroon": ["2 dotted teal", "3 striped fuchsia"],
        "striped indigo": ["2 dim crimson"],
        "shiny green": ["5 mirrored cyan", "5 faded red", "1 light silver", "4 mirrored black"],
        "clear indigo": ["2 faded gray", "2 mirrored green"],
        "vibrant magenta": ["4 muted silver", "3 bright crimson"],
        "mirrored violet": ["1 dull blue"],
        "clear yellow": ["1 plaid purple", "2 vibrant crimson", "3 faded white", "4 plaid gold"],
        "light white": ["4 clear magenta", "4 drab green", "2 clear chartreuse"],
        "striped brown": ["4 drab gold", "4 plaid red", "2 dim coral", "4 dim teal"],
        "pale crimson": ["4 dim green", "2 striped crimson", "1 striped coral", "3 dark salmon"],
        "dull olive": ["1 striped yellow", "2 bright aqua"],
        "dark olive": ["2 faded indigo", "4 dim orange", "5 shiny silver", "5 dotted turquoise"],
        "drab chartreuse": ["1 shiny olive", "1 posh tomato", "1 dark turquoise"],
        "pale green": ["3 pale gray", "1 dim violet", "3 striped crimson", "3 faded cyan"],
        "light gray": ["2 pale white", "1 dark beige", "1 clear purple"],
        "plaid olive": ["5 drab aqua", "1 plaid bronze", "4 clear brown"],
        "mirrored indigo": ["3 striped bronze", "3 faded green", "2 dotted green", "3 dull olive"],
        "wavy brown": ["4 pale maroon"],
        "shiny lime": ["2 posh gold", "5 posh black"],
        "mirrored silver": ["4 pale cyan", "1 bright bronze", "1 mirrored blue"],
        "shiny red": ["2 wavy purple", "5 drab yellow"],
        "light coral": ["2 pale gold"],
        "posh olive": ["2 bright aqua"],
        "striped black": ["3 bright blue", "1 light salmon", "1 mirrored salmon"],
        "dotted lime": ["5 muted indigo", "2 striped coral", "1 shiny orange", "4 dim black"],
        "wavy fuchsia": ["4 clear magenta"],
        "light plum": ["3 shiny maroon"],
        "shiny brown": ["1 faded brown", "5 light teal"],
        "clear tan": ["3 dark teal", "2 bright plum"],
        "pale violet": ["1 clear turquoise", "4 dark tan", "3 muted green", "3 posh magenta"],
        "plaid coral": ["2 faded red", "1 faded indigo", "4 striped blue", "5 vibrant maroon"],
        "drab red": ["3 mirrored white", "5 drab tomato", "3 vibrant chartreuse", "2 faded crimson"],
        "wavy chartreuse": ["1 bright brown", "2 vibrant aqua", "2 drab teal"],
        "dull turquoise": ["1 dotted chartreuse", "1 wavy lime", "1 faded gold"],
        "wavy tomato": ["4 bright orange", "4 shiny fuchsia", "1 bright gray", "1 posh violet"],
        "mirrored lime": ["1 vibrant salmon", "5 dull white", "5 dotted lavender", "1 dull yellow"],
        "muted white": ["4 muted olive", "3 mirrored green", "2 striped coral"],
        "muted red": ["3 pale indigo", "2 dim violet", "2 bright red"],
        "dotted lavender": ["1 clear indigo", "5 muted cyan", "5 plaid gray", "2 plaid aqua"],
        "light lavender": ["3 drab tomato", "1 wavy tan", "1 muted magenta", "1 striped magenta"],
        "faded gray": ["4 faded cyan"],
        "dark plum": ["5 dim violet", "1 light teal", "3 faded brown", "1 plaid gold"],
        "vibrant bronze": ["1 drab gray", "2 faded gray"],
        "clear white": ["2 dark fuchsia", "2 dark gray"],
        "pale beige": ["1 mirrored fuchsia"],
        "bright chartreuse": ["3 clear crimson"],
        "drab gray": ["2 faded gray", "4 posh orange", "3 dull teal", "4 shiny plum"],
        "wavy black": ["1 pale maroon"],
        "dark beige": ["1 faded gray"],
        "dark violet": ["1 muted tan", "5 faded brown", "3 plaid black"],
        "dim beige": ["1 dotted turquoise", "5 dim teal", "3 mirrored crimson"],
        "posh silver": ["3 striped orange", "4 posh teal"],
        "muted cyan": ["2 drab salmon", "1 pale olive", "2 dark plum"],
        "dark indigo": ["2 dim magenta", "3 bright orange", "4 clear white"],
        "dull violet": ["2 pale bronze", "2 mirrored blue"],
        "pale teal": ["5 striped maroon", "3 pale gray"],
        "bright green": ["4 drab green", "3 drab indigo", "5 dull blue"],
        "posh violet": ["5 wavy white"],
        "clear brown": ["no other"]
    };

    // Parse out an individual item from the list
    function parseItem(item) {
        var itemCount = Number((item.match(/^\d+/) || ['0'])[0]);
        var itemColour = item.replace(/^[0-9 ]+/, '');

        return { 'colour': itemColour, 'count': itemCount };
    }

    function countBags(bagArray, inCount) {
        var bagCount = 0;
        for (var i = 0; i < bagArray.length; i++) {
            var bagData = parseItem(bagArray[i]);
            if (bagData.count !== 0) {
                bagCount += (bagData.count + (bagData.count * countBags(data[bagData.colour], bagData.count)));
            } else {
                return 0;
            }
        }

        return bagCount;
    }

    (function () {
        var coloursList = { 'shiny gold': false };
        var newColoursFound = -1;

        while (newColoursFound !== 0) {
            newColoursFound = 0;

            for (searchKey in coloursList) {
                for (key in data) {
                    var colourFound = data[key].join(',').indexOf(searchKey) !== -1;
                    if (colourFound) {
                        if (!coloursList.hasOwnProperty(key)) {
                            coloursList[key] = true;
                            newColoursFound += 1;
                        }
                    }
                }
            }
        }

        console.log(`There are ${Object.keys(coloursList).length - 1} bags that could contain a "Shiny Gold" bag.`);
debugger
        // Part 2:  How many bags inside a single Shiny Gold bag?
        var startItem = data['shiny gold'];
        var totalBags = countBags(startItem, 0);

        console.log(`There are ${totalBags} bags contained in your single shiny gold bag.`);
    })();
}